services:
  web:
    build:
      context: ./web
      target: ${NODE_ENV:-production}
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_API_URL: ${API_URL}
    ports:
      - "${WEB_PORT}:3000"
    restart: unless-stopped
    networks:
      - internal

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
