services:
  web:
    build:
      target: ${NODE_ENV:-development}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./web:/app

  api:
    build:
      target: ${NODE_ENV:-development}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./api:/app
