services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
